import qrcode as qr
from telegram import Update
from telegram.ext import Updater ,Application ,CommandHandler ,MessageHandler,filters,ContextTypes

bot_api="7681906379:AAGsM-gpLxdt0AKUtjXHrcZ6yeJ6fC4rPnc"

def qr_code_generator(text):
    
    qr_code = qr.make(text)
    qr_code.save("qrcode.png")

async def start(update:Update ,context:ContextTypes.DEFAULT_TYPE):
    await update.message.reply_text("Please Send Your Text. It generates QR codes from text.")

async def about(update:Update,context:ContextTypes.DEFAULT_TYPE):
    await update.message.reply_text("This is a simple QR code generator bot Generated by SIKANDER.")

async def help_command(update:Update,context:ContextTypes.DEFAULT_TYPE):
    await update.message.reply_text("Simpley send your text \nBot automaticaly make QR code of given text for you")

async def handel_text(update:Update, context=ContextTypes.DEFAULT_TYPE):
    user_text=update.message.text
    qr_code_generator(user_text)

    with open("qrcode.png","rb") as photo:
        await update.message.reply_photo(photo)

if __name__=="__main__":
    app=Application.builder().token(bot_api).build()

    app.add_handler(CommandHandler("start",start))
    app.add_handler(CommandHandler("help",help_command))
    app.add_handler(CommandHandler("about",about))
    app.add_handler(MessageHandler(filters.TEXT & ~filters.COMMAND,handel_text))

    print("bot is start")
    app.run_polling()
